services:
  - type: web
    name: journalplus
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn journalplus.wsgi:application"
    staticPublishPath: static
    routes:
      - type: rewrite
        source: /media/(.*)
        destination: /media/\1
        status: 200
