# Generated by Django 4.2.23 on 2025-08-04 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('trade_setup_strategy', models.CharField(choices=[('breakout', 'Breakout'), ('reversal', 'Reversal'), ('scalping', 'Scalping'), ('other', 'Other')], max_length=20)),
                ('trade_direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_date', models.DateField()),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trade_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trade_outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trade_images/')),
                ('trade_category', models.CharField(choices=[('intraday', 'Intraday'), ('swing', 'Swing'), ('fno', 'F&O')], max_length=10)),
                ('is_swing_trade', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
