# Generated by Django 4.2.23 on 2025-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltrade',
            name='trade_symbol',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
